name: Check Release

on:
  pull_request:
    types:
      - labeled

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Retrieve the current PR number and body
      # -----------------------------
      - uses: 8BitJonny/gh-get-current-pr@2.0.0
        id: PR
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Verbose setting SHA when using Pull_Request event trigger to fix #16
          sha: ${{ github.event.pull_request.head.sha }}
          # Only return if PR is still open
          filterOutClosed: true
          # Only return if PR is not in draft state
          filterOutDraft: 1
      
      # Find any previous bot comments so we can update them
      # -----------------------------
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: FindComment
        with:
          issue-number: ${{ steps.PR.outputs.number }}
          body-includes: Release Check

      - uses: actions-ecosystem/action-release-label@v1
        id: release-label
        if: ${{ startsWith(github.event.label.name, 'release/') }}

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          semver_only: true

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: ${{ steps.release-label.outputs.level }}
          
      # Post status back
      # -----------------------------
      - name: Post Comment (Passed)
        if: success() && steps.bump-semver.outputs.new_version != null
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.FindComment.outputs.comment-id }}
          issue-number: ${{ steps.PR.outputs.number }}
          body: |
            ## Release Check
            This PR will update [${{ github.repository }}](https://github.com/${{ github.repository }}) from [${{ steps.get-latest-tag.outputs.tag }}](https://github.com/${{ github.repository }}/releases/tag/${{ steps.get-latest-tag.outputs.tag }}) to ${{ steps.bump-semver.outputs.new_version }} :rocket:
            If this update isn't as you expected, you may want to change or remove the *release label*.
          edit-mode: replace
          reactions: rocket
